name: Smoke testing

permissions:
  contents: read
  actions: read
  checks: write

on:
  workflow_dispatch:
    inputs:
      grid_url:
        required: true
        type: string
        description: Grid to run tests on (local by default)
        default: http://localhost:4444

      chrome_131_0:
        description: 'Chrome (131.0)'
        required: false
        type: boolean

jobs:
  TestChrome_131_0:
    name: Test Chrome 131.0
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.chrome_131_0 == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Launch standalone grid - Chrome
        if: ${{ contains(github.event.inputs.grid_url, 'localhost') }}
        run: |
          docker run --name grid_container -d -p 4444:4444 --shm-size=2gb selenium/standalone-chrome:131.0-chromedriver-131.0-grid-4.27.0-20250101

      - name: Run Tests
        run: |
          export BROWSER=chrome
          export GRID_URL=${{ github.event.inputs.grid_url }}
          
          mvn -q test -Dtest=selenium.SmokeTest
          
          # Tear down grid if exists
          docker stop grid_container || true

      - name: Upload Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: smoke-test-results
          path: target/surefire-reports/TEST-*.xml

  GenerateTestReport:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs: TestChrome_131_0  # This job runs only after TestChrome_131_0 finishes
    steps:
      - name: Download Test Results
        uses: actions/download-artifact@v3
        with:
          name: smoke-test-results
          path: target/surefire-reports/

      - name: Generate Report
        uses: dorny/test-reporter@v1
        with:
          name: Chrome Test Report
          path: target/surefire-reports/TEST-*.xml
          reporter: java-junit